### ISSUE TITLE
stage update failure / token selected error 

### ISSUE THREAD

**Issue by stevetrynext** [milaabl/xw-react-typescript-app#1]
If you connect your wallet, the view will not change to buy tokens. You need to refresh the page that the form will change. 
Furthermore if you select USDT it is still ETH selected as currency

**Comment by stevetrynext** [comment]
furthermore it does not load the contract values if you just load the page
(dev mode)

**Comment by milaabl** [comment]
@stevetrynext, please test the updated version, I worked on the fixes and made some more necessary updates that I find beneficial for the UX and testing (e.g. each time the user switches the `tokenIn`, updating the amount of XUIRIN tokens that the user will receive for his USDT/ETH deposit), and *— finally —* showing how much XUIRIN presale tokens the user has. :)
